version: '2'

services:
    eneon_db:
        image: mysql:5.5.53
        #volumes:
        #- "./eneon-data:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_DATABASE: eneon_db
            MYSQL_ROOT_PASSWORD: mysql
    
    eneon_drupal-with-xdebug:
        depends_on:
            - eneon_db
        build: . 
        volumes:
            # Uncomment if you want your local drupal instance
            # mapped into the container
            #- "./drupal:/var/www/html/"
            # The following volumes map the actual ENEON modules
            # into the container
            - "./eneon:/var/www/html/sites/all/modules/eneon"
            - "./eneon_theme:/var/www/html/sites/all/themes/eneon_theme"
            # Essential setup instructions when container starts
            - "./config/launch.sh:/usr/local/bin/startup"
            # Example config to map root context. For this make sure 
            #  - to add `$base_url = 'http://localhost/<alias>'` to settings.php
            #  - set `RewriteBase /<alias>` in Drupal's .htaccess file
            #- "./config/docker-php.conf:/etc/apache2/conf-available/docker-php.conf"
        links:
            - eneon_db
        ports:
            - 8000:80
        restart: always

        
